### ISSUE TITLE
Unable to replace core

### ISSUE THREAD

**Issue by nyacat** [mellow-io/go-tun2socks#2]
Once I wanna replace core.exe in mellow, it fail to start, mellow log shows missing args "-stats"

And I try to add in [main,go](https://github.com/mellow-io/go-tun2socks/blob/master/cmd/tun2socks/main.go), it started, but something strange happend. I can watch youtube video, but cannot play any games

Code added.
L125:
`args.Stats= flag.Bool("stats", false, "test stats")`

**Comment by lizkes** [comment]
use "go build -tags", check  [this](https://golang.org/pkg/go/build/#hdr-Build_Constraints)  for detail

**Comment by nyacat** [comment]
This doesn't work either, and I've download release and replace within mellow's core.exe, got the same error

**Comment by eycorsican** [comment]
Upgrade Mellow to the latest version.

**Comment by nyacat** [comment]
fixed,thanks
